import enum


class GameType(enum.Enum):
    TOP_VS_BOTTOM = 'TOP_VS_BOTTOM'
    MELEE = 'MELEE'
    FREE_FOR_ALL = 'FREE_FOR_ALL'
    ONE_ON_ONE = 'ONE_ON_ONE'
    USE_MAP_SETTINGS = 'USE_MAP_SETTINGS'
    CAPTURE_THE_FLAG = 'CAPTURE_THE_FLAG'
    GREED = 'GREED'
    SLAUGHTER = 'SLAUGHTER'
    SUDDEN_DEATH = 'SUDDEN_DEATH'
    TEAM_MELEE = 'TEAM_MELEE'
    TEAM_FREE_FOR_ALL = 'TEAM_FREE_FOR_ALL'
    TEAM_CAPTURE_THE_FLAG = 'TEAM_CAPTURE_THE_FLAG'
